language: go
dist: trusty
sudo: required
os:
- linux
- osx
before_script:
- make dep
script:
- make go-gen
- make go-test
before_deploy:
- ./tools/release.sh
deploy:
  provider: releases
  api_key:
    secure: __TRAVIS_TOKEN_PLACEHOLDER__
  file: rubberdoc-$TRAVIS_TAG.${TRAVIS_OS_NAME/osx/darwin}-amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true